In [2]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
b=np.array([1,2,3.7,4.7,5.5])
print(b)
print(type(b))

[1.  2.  3.7 4.7 5.5]
<class 'numpy.ndarray'>


In [4]:
c=np.array(['a','b','c','d'])
print(c)
print(type(c))

['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>


In [5]:
#checking data type of array
a.dtype

dtype('int32')

In [6]:
b.dtype

dtype('float64')

In [7]:
c.dtype

dtype('<U1')

In [8]:
# to check dimension of array
a.ndim

1

In [9]:
# to make a 2-D array
#a=np.array([[ist row],[2nd row],[3rd row]])


In [10]:
a=np.array([[1,2,3,4],[3,4,5,6],[3,8,9,10]])
print(a)
print(type(a))

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 3  8  9 10]]
<class 'numpy.ndarray'>


In [11]:
numpy_array = np.array([[1,3], [3,4], [5,6]])

print("\n A numpy array: \n" , numpy_array)
print("\n Type : ", type(numpy_array))
print("\n Dtype : " , numpy_array.dtype)
print("\n NDim : " , numpy_array.ndim) # Dimensions of numpy array
print("\n ItemSize : " , numpy_array.itemsize) # size of a single element in the numpy array

#Shape of numpy array in (rows,columns)the shape of an array is a tuple of integers giving 
#the size of the array along each dimension.

print("\n Shape : " , numpy_array.shape)
print("\n NBytes : " , numpy_array.nbytes)


 A numpy array: 
 [[1 3]
 [3 4]
 [5 6]]

 Type :  <class 'numpy.ndarray'>

 Dtype :  int32

 NDim :  2

 ItemSize :  4

 Shape :  (3, 2)

 NBytes :  24


In [5]:
x=np.array([1.7,2.9,3.7,4.7,5.5])
print(x)
print(type(x))
print(x.ndim)
print(x.shape)
print(x.nbytes)


[1.7 2.9 3.7 4.7 5.5]
<class 'numpy.ndarray'>
1
(5,)
40


In [15]:
new =np.array([1,2,3.7,4.7,5.5])
print("\n A numpy array: \n" , new)
print("\n Type : ", type(new))
print("\n Dtype : " , new.dtype)
print("\n NDim : " , new.ndim)
print("\n ItemSize : " , new.itemsize) 


print("\n Shape : " , new.shape)
print("\n NBytes : " , new.nbytes)


 A numpy array: 
 [1.  2.  3.7 4.7 5.5]

 Type :  <class 'numpy.ndarray'>

 Dtype :  float64

 NDim :  1

 ItemSize :  8

 Shape :  (5,)

 NBytes :  40


In [19]:
y= np.array([["j","k"], ["g","a"], ["5","6"]])
print(y)

[['j' 'k']
 ['g' 'a']
 ['5' '6']]


In [20]:
# make a 3*2 char matrix

new = np.array([['abs','bgh'], ['123','dhhjk'], ['3345','ffgh']])
new
print("\n Type : ", type(new))
print("\n Dtype : " , new.dtype)
print("\n NDim : " , new.ndim)
print("\n ItemSize : " , new.itemsize) 


print("\n Shape : " , new.shape)
print("\n NBytes : " , new.nbytes)


 Type :  <class 'numpy.ndarray'>

 Dtype :  <U5

 NDim :  2

 ItemSize :  20

 Shape :  (3, 2)

 NBytes :  120


In [21]:
#External Typecasting of numpy arrays

arr_fl = np.array([[1,2], [3,4], [5,6]])
print( arr_fl)
print(arr_fl.dtype)

[[1 2]
 [3 4]
 [5 6]]
int32


In [22]:
arr_fl = np.array([[1,2], [3,4], [5,6]] , dtype = np.float64)
print(" A Float Array: \n" , arr_fl)
print(arr_fl.dtype)

 A Float Array: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
float64


In [27]:
# can you predict the answer
arr_comp = np.array([[1.1,2.2], [3.5,4.6], [5.2,6.1]])
print(arr_comp)
arr_comp = np.array([[1.1,2.2], [3.5,4.6], [5.2,6.1]] , dtype = np.int32)
print(" \n\nInteger Array: \n" , arr_comp)

[[1.1 2.2]
 [3.5 4.6]
 [5.2 6.1]]
 

Integer Array: 
 [[1 2]
 [3 4]
 [5 6]]


In [28]:
# creating array of zeros

z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# creating array of ones

o=np.ones((4,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# for creating identity matrix
e=np.eye((5))
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
#Array filled with a constant

full_array = np.full((4,7), 2.5)
full_array

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

In [32]:
#Array with arange() function

A = np.arange(7)
print("An array with range 7 : " , A)
print(type(A))
print(A.dtype)
print(A.ndim)
print(A.shape)

An array with range 7 :  [0 1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32
1
(7,)


In [33]:
b=np.arange(4,21)
print(b)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [34]:
b=np.arange(4,21,2)
print(b)

[ 4  6  8 10 12 14 16 18 20]


In [37]:
b=np.arange(3,28,3)
print(b)

[ 3  6  9 12 15 18 21 24 27]


In [39]:
# To generate Random nos.

ran_arr = np.random.random((4, 2))
print(ran_arr)

[[0.71611666 0.31172593]
 [0.90132199 0.89401013]
 [0.69963558 0.72808608]
 [0.30384454 0.46980599]]


In [40]:
# to generate integer random nos.

np.random.randint(0, 10, (3, 4))

array([[5, 0, 9, 5],
       [1, 4, 9, 7],
       [5, 5, 2, 6]])

In [9]:
import numpy as np

In [13]:
#numpy with strings
a=np.array(["ab"])
b=np.array(["cd"])
print(np.char.add(a,b))

['abcd']


In [25]:
array1=np.array([["hey","user"],["welcom","to the site"]])
array2=np.array([["123"],["345"]])
print("\n array 1 is:\n",array1)
print("\n array 2 is: \n",array2)
c=np.char.add(array1,array2)
print("\n concatinated array \n",c)



 array 1 is:
 [['hey' 'user']
 ['welcom' 'to the site']]

 array 2 is: 
 [['123']
 ['345']]

 concatinated array 
 [['hey123' 'user123']
 ['welcom345' 'to the site345']]


In [27]:
#replication of array elements
arr=np.array([["xyz","no"],["ha","jo"]])
print("\n array is \n",arr)
mult_array=np.char.multiply(arr,3)
print(mult_array)


 array is 
 [['xyz' 'no']
 ['ha' 'jo']]
[['xyzxyzxyz' 'nonono']
 ['hahaha' 'jojojo']]


In [31]:
#capitalizing
n_array=np.array(["my name is gauri"])
cap=np.char.capitalize(n_array)
print(cap)

['My name is gauri']


In [33]:
c_array=([["gaurI","OSHU"],["aSHI","Har"]])
cap=np.char.capitalize(c_array)
print(cap)

[['Gauri' 'Oshu']
 ['Ashi' 'Har']]


In [36]:
#converting to lower and upper case
x=np.array([["GAUri","hAr"],["miss","bOb"]])
print("\n",x)
uc=np.char.upper(x)
print(uc)
lc=np.char.lower(x)
print(lc)


 [['GAUri' 'hAr']
 ['miss' 'bOb']]
[['GAURI' 'HAR']
 ['MISS' 'BOB']]
[['gauri' 'har']
 ['miss' 'bob']]


In [37]:
#splitting string        #converts array into list and split 
s=np.array(["hey how are you"])
sp=np.char.split(s)
print(sp)

[list(['hey', 'how', 'are', 'you'])]


In [44]:
s=np.array(["hey, how are you, naman"])
sp=np.char.split(s,sep=",")
print(sp)

[list(['hey', ' how are you', ' naman'])]


In [55]:
#strip
print(np.char.strip(["hey how who"],"h"))


['ey how who']


In [62]:
print(np.char.strip(["hey", "howe","whoh"],"h"))


['ey' 'owe' 'who']


In [61]:
print(np.char.strip(["hey", "howe","whoh"],"heo"))

['y' 'w' 'w']


##join

In [65]:
#ex-input["abcd","hello","good"]
#outpit["a*b*c*d","h-e-l-l-o","g@o@o@d"]
a=np.char.join(["*","-","@"],["abcd","hello","good"])
print(a)

['a*b*c*d' 'h-e-l-l-o' 'g@o@o@d']


In [67]:
#Replacing with specific contend
a=np.char.replace("Gauri is amazing","amazing","the best")
print(a)

Gauri is the best


In [68]:
a=np.array([["he likes painting","he likes yoga"],["she likes to travel ","she likes him"]])
print(a)
rep=np.char.replace(a,"likes","love")
print(rep)

[['he likes painting' 'he likes yoga']
 ['she likes to travel ' 'she likes him']]
[['he love painting' 'he love yoga']
 ['she love to travel ' 'she love him']]


In [72]:
#array manipulation in multidimentional array
a=np.array([[2,3,4],[5,6,7],[8,9,10]])
print(a)
print(a[1,1])

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
6


In [80]:
a=np.array([[2,3,4],[5,6,7],[8,9,10],[4,7,6,],[12,6,54]])
print(a)
print("new array \n",a[2:4,0:2])

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [ 4  7  6]
 [12  6 54]]
new array 
 [[8 9]
 [4 7]]


In [83]:
print(a)
print(a[:,: :2])

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [ 4  7  6]
 [12  6 54]]
[[ 2  4]
 [ 5  7]
 [ 8 10]
 [ 4  6]
 [12 54]]


In [87]:
print(a[: :3, : :])

[[2 3 4]
 [4 7 6]]


In [111]:
#Reshaping
                       ##CAN CONVERT ONE D ARRAY INTO 2 D ARRAY

arr=np.arange(1,13)
print(arr)
resh=arr.reshape(4,3)
print("\n",resh)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [103]:
#ex- take 12 elements using arange(),convert it into all possible 2d combos
a=np.arange(1,13)

#print(a.reshape(2,6))
#print(a.reshape(3,4))
#print(a.reshape(6,2))
print(a.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [114]:
#Resizeing an array
a=np.array([[1,2,3,9],[4,5,6,8],[7,8,9,45]])
print(np.resize(a,(3,4)))

[[ 1  2  3  9]
 [ 4  5  6  8]
 [ 7  8  9 45]]


In [116]:
print(np.resize(a,(5,5)))

[[ 1  2  3  9  4]
 [ 5  6  8  7  8]
 [ 9 45  1  2  3]
 [ 9  4  5  6  8]
 [ 7  8  9 45  1]]
