In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

1.2.4


##seies in pandas

In [4]:
s = pd.Series([0.2, 0.5, 0.75, 1.6, 0.5, 0.2])
#series
print("Pandas Series:\n" , s)
print(type(s))

Pandas Series:
 0    0.20
1    0.50
2    0.75
3    1.60
4    0.50
5    0.20
dtype: float64
<class 'pandas.core.series.Series'>


In [5]:
l=[4,7,2,6,8]
s=pd.Series(l)
s

0    4
1    7
2    2
3    6
4    8
dtype: int64

In [6]:
s2=pd.Series([1,2,'3','4'])
s2

0    1
1    2
2    3
3    4
dtype: object

In [7]:
s2=pd.Series([1,2,4.6,7.8])
s2

0    1.0
1    2.0
2    4.6
3    7.8
dtype: float64

In [8]:
# To find unique values in a series
a=pd.Series([2,2,4,5,7,3,2,2,4])
print(a)
a.unique()

0    2
1    2
2    4
3    5
4    7
5    3
6    2
7    2
8    4
dtype: int64


array([2, 4, 5, 7, 3], dtype=int64)

In [9]:
#if only want to print values of series
s = pd.Series([0.2, 0.5, 0.75, 1.6, 0.5, 0.2])
print(s)
print("Series.values: ",s.values)

0    0.20
1    0.50
2    0.75
3    1.60
4    0.50
5    0.20
dtype: float64
Series.values:  [0.2  0.5  0.75 1.6  0.5  0.2 ]


In [10]:
print("Index of Series: ", s.index)

Index of Series:  RangeIndex(start=0, stop=6, step=1)


In [11]:
i=[100,200,300,400]
v=[5,6,7,8]
#s=pd.Series(i,v)
#s=pd.Series(v,i)
s=pd.Series(index=i,data=v)
s

100    5
200    6
300    7
400    8
dtype: int64

In [12]:
i=[100,200,300,400]
v=[5,6,7,8]
s=pd.Series(i,v)
#s=pd.Series(v,i)
#s=pd.Series(index=i,data=v)
s

5    100
6    200
7    300
8    400
dtype: int64

In [49]:
i=[100,200,300,400]
v=[5,6,7,8]
#s=pd.Series(i,v)
s=pd.Series(v,i)
#s=pd.Series(index=i,data=v)
s

100    5
200    6
300    7
400    8
dtype: int64

In [14]:
s2=pd.Series([100,200,300,400], index=['a','b','c','d'])
s2


a    100
b    200
c    300
d    400
dtype: int64

In [15]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [16]:
List=[20, 15, 42, 33, 94, 8, 5]
print("List is: " , List)
print(type(List))
ser_list=pd.Series(List)
print("Series from List: \n",ser_list)
print(type(ser_list))

List is:  [20, 15, 42, 33, 94, 8, 5]
<class 'list'>
Series from List: 
 0    20
1    15
2    42
3    33
4    94
5     8
6     5
dtype: int64
<class 'pandas.core.series.Series'>


In [17]:
#creating a series uning numpy array

In [18]:
import numpy as np

In [19]:
np_arr=np.random.random(5)
print("Array is: ", np_arr)

i=['a','b','c','d','e']
ser_arr=pd.Series(np_arr,index=i)
print("Series from Numpy Array: \n", ser_arr)

Array is:  [0.56205374 0.94041328 0.72259564 0.21102142 0.20770348]
Series from Numpy Array: 
 a    0.562054
b    0.940413
c    0.722596
d    0.211021
e    0.207703
dtype: float64


In [51]:
np_arr=np.random.randint(0,5,6)
print("Array is: ", np_arr)

i=['a','b','c','d','e','f']
ser_arr=pd.Series(np_arr,index=i)
print("Series from Numpy Array: \n", ser_arr)

Array is:  [3 3 4 3 3 4]
Series from Numpy Array: 
 a    3
b    3
c    4
d    3
e    3
f    4
dtype: int32


In [21]:
np_arr=np.random.random(7)
print("Array is: ", np_arr)
i=np_arr=np.random.randint(0,8,7)
ser_arr=pd.Series(np_arr,np_index=i)
print("Series from Numpy Array: \n", ser_arr)

ser_arr=pd.Series(np_arr,np_index=i)
print("Series from Numpy Array: \n", ser_arr)



Array is:  [0.3448871  0.70721388 0.22771053 0.2620252  0.40373653 0.89482183
 0.78562528]


TypeError: __init__() got an unexpected keyword argument 'np_index'

In [22]:
ser_arr=pd.Series([3,7,8,2,1,10])
ser_arr

0     3
1     7
2     8
3     2
4     1
5    10
dtype: int64

In [23]:
# Applying functions in Series

print(ser_arr.max())
print(ser_arr.min())
print(ser_arr.sum())

print(np.mean(ser_arr))
print(np.median(ser_arr))

10
1
31
5.166666666666667
5.0


In [25]:
#creating series from dictionary
d={'monkey':153 ,'rat':212 ,'cotton':334 ,'fan':98}
print("Dictionary is: ", d)

Dictionary is:  {'monkey': 153, 'rat': 212, 'cotton': 334, 'fan': 98}


In [26]:
s=pd.Series(d)
s

monkey    153
rat       212
cotton    334
fan        98
dtype: int64

In [27]:
s.index

Index(['monkey', 'rat', 'cotton', 'fan'], dtype='object')

In [28]:
s.values

array([153, 212, 334,  98], dtype=int64)

In [29]:
# if i want to extract a specific index position what will be the code

s1=pd.Series(['A','B','C','D','E'])
print(s1)

print(s1[2])

0    A
1    B
2    C
3    D
4    E
dtype: object
C


In [30]:
#inset a value in seies
s1[5] ='F'
print("\n After updation : \n",s1)
#update a value in series
s1[3] ='K'
print("\n After updation : \n",s1)


 After updation : 
 0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

 After updation : 
 0    A
1    B
2    C
3    K
4    E
5    F
dtype: object


In [31]:
s
print(s['monkey' : 'cotton'])

monkey    153
rat       212
cotton    334
dtype: int64


In [32]:
d = pd.Series(['a', 'b', 'c','d','e','f'], index=[1, 3, 5,7,9,11])
print("Series : \n",d)

Series : 
 1     a
3     b
5     c
7     d
9     e
11    f
dtype: object


In [33]:
d[0:4]

1    a
3    b
5    c
7    d
dtype: object

In [34]:
d = pd.Series(['a', 'b', 'c','d','e','f'], index=['1', '3', '5','7','9','11'])
print("Series : \n",d)

Series : 
 1     a
3     b
5     c
7     d
9     e
11    f
dtype: object


In [35]:
d[0:4]


1    a
3    b
5    c
7    d
dtype: object

In [36]:

d['3':'9']

3    b
5    c
7    d
9    e
dtype: object

In [37]:
##joining seies

In [38]:
# joing two Series
s1= pd.Series([0,1,2,3,4],index=['A','B','C','D','E'])

s1

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [39]:
s3 = pd.Series([1,2,3,4], index = ['a','b','c','d'])
print('s3: \n',s3)


s3: 
 a    1
b    2
c    3
d    4
dtype: int64


In [42]:
s4 = s1.append(s3)
print('Appending a series: \n',s4 )

Appending a series: 
 A    0
B    1
C    2
D    3
E    4
a    1
b    2
c    3
d    4
dtype: int64


In [43]:
##arthmetic function

In [44]:
s5=pd.Series([6,7,8,9,5])
s6=pd.Series([0,1,2,3,4,6,7])
print('Series are : \n',s5, '\n', s6)

Series are : 
 0    6
1    7
2    8
3    9
4    5
dtype: int64 
 0    0
1    1
2    2
3    3
4    4
5    6
6    7
dtype: int64


In [45]:
print('Addition of series: \n', s6.add(s5))

Addition of series: 
 0     6.0
1     8.0
2    10.0
3    12.0
4     9.0
5     NaN
6     NaN
dtype: float64


In [46]:
print('Subtraction of series: \n', s6.sub(s5))

Subtraction of series: 
 0   -6.0
1   -6.0
2   -6.0
3   -6.0
4   -1.0
5    NaN
6    NaN
dtype: float64


In [47]:
s6.multiply(s5)

0     0.0
1     7.0
2    16.0
3    27.0
4    20.0
5     NaN
6     NaN
dtype: float64

In [48]:
s6.divide(s5)

0    0.000000
1    0.142857
2    0.250000
3    0.333333
4    0.800000
5         NaN
6         NaN
dtype: float64

In [52]:
#pandas dataframe

In [53]:
#creating datafeame using series

In [54]:
import pandas as pd

In [55]:
d1={'a':1,'b':2,'c':3}
s1=pd.Series(d1)
print(s1)
print(type(s1))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [56]:
d2={'a':5,'b':6,'c':7}
s2=pd.Series(d2)
print(s2)
print(type(s2))

a    5
b    6
c    7
dtype: int64
<class 'pandas.core.series.Series'>


In [57]:
df = pd.DataFrame({'C1': s1,  'C2': s2})
print(df)
print(type(df))

   C1  C2
a   1   5
b   2   6
c   3   7
<class 'pandas.core.frame.DataFrame'>


In [58]:
df = pd.DataFrame({'Column-1': s2,  'Column-2': s1})
print(df)
print(type(df))

   Column-1  Column-2
a         5         1
b         6         2
c         7         3
<class 'pandas.core.frame.DataFrame'>


In [59]:
population_d = {'California': 3833, 'Texas': 8193,
                'New York': 6511, 'Florida': 5560, 'Ohio': 1135}  
#print(population_d, type(population_d))
population = pd.Series(population_d)
print(population)

California    3833
Texas         8193
New York      6511
Florida       5560
Ohio          1135
dtype: int64


In [60]:
area_d = {'California': 423967, 'Texas': 695662, 'New York': 141297,   
             'Florida': 170312, 'Ohio': 149995}
area = pd.Series(area_d) 
print(area)

California    423967
Texas         695662
New York      141297
Florida       170312
Ohio          149995
dtype: int64


In [61]:
states = pd.DataFrame({'Population': population,  'Area': area})
states

Population    Area
California        3833  423967
Texas             8193  695662
New York          6511  141297
Florida           5560  170312
Ohio              1135  149995

In [62]:
print('Index values \n', states.index)
print(' Column names\n', states.columns)

Index values 
 Index(['California', 'Texas', 'New York', 'Florida', 'Ohio'], dtype='object')
 Column names
 Index(['Population', 'Area'], dtype='object')


In [63]:
states.Area


California    423967
Texas         695662
New York      141297
Florida       170312
Ohio          149995
Name: Area, dtype: int64

In [64]:
states['Area']

California    423967
Texas         695662
New York      141297
Florida       170312
Ohio          149995
Name: Area, dtype: int64

In [65]:
#create dataframe using numpy array

In [66]:
import numpy as np

#num_arr = np.random.randint(8,size=4)
num_arr = np.random.randint(10,size=(6,4)) #Import numpy random arrays
print("Array is : \n", num_arr)

Array is : 
 [[2 9 0 0]
 [2 7 3 7]
 [1 7 9 2]
 [5 0 5 6]
 [6 8 9 6]
 [3 4 1 8]]


In [67]:
#giving column headings

cols=['A','B','C','D']
i=['i', 'ii', 'iii', 'iv', 'v', 'vi']
#df1=pd.DataFrame(num_arr)
df1=pd.DataFrame(num_arr,columns=cols, index = i)
print('\n Data Frame from numpy array is : \n')
df1


 Data Frame from numpy array is : 



A  B  C  D
i    2  9  0  0
ii   2  7  3  7
iii  1  7  9  2
iv   5  0  5  6
v    6  8  9  6
vi   3  4  1  8

In [70]:
df1.index


Index(['i', 'ii', 'iii', 'iv', 'v', 'vi'], dtype='object')

In [69]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [71]:
# summary of data frame
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, i to vi
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int32
 1   B       6 non-null      int32
 2   C       6 non-null      int32
 3   D       6 non-null      int32
dtypes: int32(4)
memory usage: 144.0+ bytes


In [72]:
# to see data type of cols

df1.dtypes

A    int32
B    int32
C    int32
D    int32
dtype: object

In [74]:
df1.A

i      2
ii     2
iii    1
iv     5
v      6
vi     3
Name: A, dtype: int32

In [75]:
df1[['A','D']]

A  D
i    2  0
ii   2  7
iii  1  2
iv   5  6
v    6  6
vi   3  8

In [76]:
data={'Animals': ['cat','cat','turtle','dog','dog','cat','turtle','cat','dog','dog'],
          'Age': [2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3], 
      'Visits' : [1,3,2,3,2,3,1,1,2,1], 
    'Priority' : ['y','y','n','y','n','n','n','y','n','n']}


labels=['a','b','c','d','e','f','g','h','i','j']
animals_data=pd.DataFrame(data,index=labels)
animals_data

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [77]:
animals_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Animals   10 non-null     object 
 1   Age       8 non-null      float64
 2   Visits    10 non-null     int64  
 3   Priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [78]:
# to check null values

animals_data.isnull().sum()

Animals     0
Age         2
Visits      0
Priority    0
dtype: int64

In [80]:
animals_data.head()

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n

In [81]:
animals_data.head(7)

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n

In [82]:
# to check last 5 entries

animals_data.tail()

Animals  Age  Visits Priority
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [83]:
# random sample of data

animals_data.sample(5)

Animals  Age  Visits Priority
c  turtle  0.5       2        n
a     cat  2.5       1        y
f     cat  2.0       3        n
b     cat  3.0       3        y
e     dog  5.0       2        n

In [84]:
print('\n Sorting the Data Frame name-wise : \n' , animals_data.sort_values(by = 'Animals'))


 Sorting the Data Frame name-wise : 
   Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
f     cat  2.0       3        n
h     cat  NaN       1        y
d     dog  NaN       3        y
e     dog  5.0       2        n
i     dog  7.0       2        n
j     dog  3.0       1        n
c  turtle  0.5       2        n
g  turtle  4.5       1        n


In [85]:
animals_data.sort_values(by = 'Animals')

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
f     cat  2.0       3        n
h     cat  NaN       1        y
d     dog  NaN       3        y
e     dog  5.0       2        n
i     dog  7.0       2        n
j     dog  3.0       1        n
c  turtle  0.5       2        n
g  turtle  4.5       1        n

In [86]:
animals_data.sort_values(by = 'Animals',ascending=False)

Animals  Age  Visits Priority
c  turtle  0.5       2        n
g  turtle  4.5       1        n
d     dog  NaN       3        y
e     dog  5.0       2        n
i     dog  7.0       2        n
j     dog  3.0       1        n
a     cat  2.5       1        y
b     cat  3.0       3        y
f     cat  2.0       3        n
h     cat  NaN       1        y

In [87]:
animals_data.sort_values(by = 'Age')

Animals  Age  Visits Priority
c  turtle  0.5       2        n
f     cat  2.0       3        n
a     cat  2.5       1        y
b     cat  3.0       3        y
j     dog  3.0       1        n
g  turtle  4.5       1        n
e     dog  5.0       2        n
i     dog  7.0       2        n
d     dog  NaN       3        y
h     cat  NaN       1        y

In [88]:
# to creating a copy of DF

df3=animals_data.copy()
df3

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [90]:
#aggregate function
print("Mean of the Dataframe is: \n",df3.mean())

Mean of the Dataframe is: 
 Age       3.4375
Visits    1.9000
dtype: float64


In [91]:
df3.median()

Age       3.0
Visits    2.0
dtype: float64

In [92]:
df3['Age'].mean()

3.4375

In [93]:
# to find statistical summary

df3.describe()

Age     Visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [95]:
df3['Visits'].sum()


19

In [96]:
df3['Age'].max()


7.0

In [97]:
df3['Age'].min()

0.5

In [98]:
##handling missing data

In [99]:
df = pd.DataFrame([[1,      np.nan, 4],    
                   [2,      3,      5],     
                   [np.nan, 4,      6]])  
print(df)
print('\n Dropping all rows having null values')
print(df.dropna())

     0    1  2
0  1.0  NaN  4
1  2.0  3.0  5
2  NaN  4.0  6

 Dropping all rows having null values
     0    1  2
1  2.0  3.0  5


In [100]:
print('\n Dropping all cols having null values')
print(df.dropna(axis='columns'))


 Dropping all cols having null values
   2
0  4
1  5
2  6


In [101]:
# Filling null values
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde')) 
print('\n')
print(data)



a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64


In [102]:
# Fills null value with a constant
print(data.fillna(0))

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64


In [103]:
print(data.fillna(method='bfill'))

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64


In [104]:
print(data.fillna(method='ffill'))

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64


In [105]:
df3

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [106]:
md_age=df3['Age'].median()
print(md_age)
df3.fillna(md_age)

3.0


Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  3.0       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  3.0       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [107]:
# saving the csv file
df3.to_csv('animal.csv')

In [108]:
# saving the excel fil
df3.to_excel('animal.xlsx',sheet_name='sheet1')